# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.openshift.expose-services="8080:http"

LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD" \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="apache, httpd"

RUN sed -i -e 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /run/httpd /etc/httpd/logs && \
    chmod -R g=u /run/httpd /etc/httpd/logs

USER 1001

EXPOSE 8080
